// Videos Data

export const videoData = [
  {
    video: require('../../storage/videos/video1.mp4'),
    postProfile: require('../../storage/images/post1.jpg'),
    title: 'Ram_Charan',
    description: 'Feel the buity of nature',
    likes: '245k',
    isLike: false,
  },
  {
    video: require('../../storage/videos/video2.mp4'),
    postProfile: require('../../storage/images/post2.jpg'),
    title: 'The_Groot',
    description: "It's a tea time",
    likes: '656k',
    isLike: false,
  },
  {
    video: require('../../storage/videos/video3.mp4'),
    postProfile: require('../../storage/images/post3.jpg'),
    title: 'loverland',
    description: 'Feel the buity of nature',
    likes: '243k',
    isLike: false,
  },
  {
    video: require('../../storage/videos/video4.mp4'),
    postProfile: require('../../storage/images/post4.jpg'),
    title: 'mr. bean',
    description: 'How cute it is !!',
    likes: '876k',
    isLike: false,
  },
];

// Friends Profile Data

export const FriendsProfileData = [
  {
    name: 'Son dep trai',
    accountName: 'LVS',
    profileImage: require('../../storage/images/profile4.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'Truong Quang Tan',
    accountName: 'TQT',
    profileImage: require('../../storage/images/profile5.jpg'),
    posts: 24,
    followers: 1253,
    following: 64,
    follow: false,
  },
  {
    name: 'Nguyen Duc Nghia',
    accountName: 'NDN',
    profileImage: require('../../storage/images/profile2.jpg'),
    posts: 21,
    followers: 7886,
    following: 32,
    follow: false,
  },
  {
    name: 'Vo Thanh An',
    accountName: 'VTA',
    profileImage: require('../../storage/images/post1.jpg'),
    posts: 123,
    followers: 64253,
    following: 32,
    follow: false,
  },
  {
    name: 'Nghia Ngu',
    accountName: 'The NN',
    profileImage: require('../../storage/images/post2.jpg'),
    posts: 56,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: 'Người Nhện Cô Đơn',
    accountName: 'Spiderman',
    profileImage: require('../../storage/images/post3.jpg'),
    posts: 452,
    followers: '564k',
    following: 31,
    follow: false,
  },
  {
    name: 'Tuấn Bịp',
    accountName: 'Mr TB',
    profileImage: require('../../storage/images/post4.jpg'),
    posts: 543,
    followers: '435k',
    following: 22,
    follow: false,
  },
  {
    name: 'Huấn Hoa Hồng',
    accountName: 'Mr HHH',
    profileImage: require('../../storage/images/post5.jpg'),
    posts: 234,
    followers: '763k',
    following: 332,
    follow: false,
  },
  {
    name: 'Khá Bảnh',
    accountName: 'KB',
    profileImage: require('../../storage/images/post6.jpg'),
    posts: 111,
    followers: 11223,
    following: 1,
    follow: false,
  },
  {
    name: 'black white man',
    accountName: 'blackWhiteBBC',
    profileImage: require('../../storage/images/post7.jpg'),
    posts: 121,
    followers: 43213,
    following: 21,
    follow: false,
  },
  {
    name: 'Ironman đã hẹo 3',
    accountName: 'Iron Man',
    profileImage: require('../../storage/images/post8.jpg'),
    posts: 432,
    followers: '987k',
    following: 24,
    follow: false,
  },
  {
    name: 'batman mồ côi 2',
    accountName: 'Batman Video Official',
    profileImage: require('../../storage/images/post9.jpg'),
    posts: '1.2k',
    followers: '1.2M',
    following: 12,
    follow: false,
  },
  {
    name: 'batman mồ côi',
    accountName: 'Mr Batman',
    profileImage: require('../../storage/images/post10.jpg'),
    posts: 533,
    followers: 64322,
    following: 123,
    follow: false,
  },
];
